# Generated by Django 6.0.6 on 2026-06-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_loanschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanschedule',
            name='is_paid',
        ),
    ]
